name: 04-unit-test-and-build
on: [workflow_dispatch]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: EsLint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [unit-tests, eslint]
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
      - name: Output information
        run: |
          echo "Author: ${{ github.actor }}"
          echo "Branch: ${{ github.ref }}"
